title: "Stevancw.com"
subtitle: "A blog by Stevan C Wing. beta 0.88"

author:
  name: Stevan C Wing
  uri: http://stevancw.com
  email: stevanw@gmail.com

# theme: bootstrap

disqus_short_name: stevancw

cache: false

content: content

production:
  # cache: true    
  # content: /var/apps/nesta/shared/content
  google_analytics_code: "UA-27412330-1"
